# The image height and width are provided in case the original image
# was resized.
BodyJoint2D reye
BodyJoint2D leye
BodyJoint2D rear
BodyJoint2D lear
BodyJoint2D nose
BodyJoint2D neck
BodyJoint2D rshoulder
BodyJoint2D lshoulder
BodyJoint2D relbow
BodyJoint2D lelbow
BodyJoint2D rwrist
BodyJoint2D lwrist
BodyJoint2D rhip
BodyJoint2D lhip
BodyJoint2D rknee
BodyJoint2D lknee
BodyJoint2D rankle
BodyJoint2D lankle
int32 image_height
int32 image_width
